FROM java
MAINTAINER frundh

ENV JTCL_VERSION 2.8.0
ENV JTCL_RELEASE jtcl-${JTCL_VERSION}

ENV TESTCL_VERSION 1.0.10
ENV TESTCL_RELEASE TesTcl-${TESTCL_VERSION}

ENV CWD_DIR /cwd/


RUN echo '# Installing some stuff'
RUN apt-get update
RUN apt-get -y install unzip sed

RUN echo '# Get JTcl'
ADD https://github.com/jtcl-project/jtcl/releases/download/${JTCL_VERSION}-release/${JTCL_RELEASE}-bin.zip /tmp/
RUN unzip /tmp/${JTCL_RELEASE}-bin.zip
RUN rm /tmp/${JTCL_RELEASE}-bin.zip

RUN echo '# Get JTcl-iRule extension to JTcl'
ADD https://github.com/downloads/landro/TesTcl/jtcl-irule.jar /${JTCL_RELEASE}/

RUN echo '# Patch jtcl shell script file'
RUN echo 'exec java -DTCLLIBPATH="$TCLLIBPATH" -cp "$CLASSPATH" $JAVA_OPTS tcl.lang.Shell ${1+"$@"}' > /${JTCL_RELEASE}/jtcl

ENV CLASSPATH /${JTCL_RELEASE}/jtcl-irule.jar:/${JTCL_RELEASE}/${JTCL_RELEASE}.jar

RUN echo '# Create symlink'
RUN ln -s /${JTCL_RELEASE}/jtcl /usr/local/bin

RUN echo '# Get TesTcl'
ADD https://github.com/landro/TesTcl/archive/v${TESTCL_VERSION}.zip /tmp/
RUN unzip /tmp/v${TESTCL_VERSION}.zip
RUN rm /tmp/v${TESTCL_VERSION}.zip

RUN echo '# Add TesTcl directory to the TCLLIBPATH environment variable'
ENV TCLLIBPATH /${TESTCL_RELEASE}

WORKDIR ${CWD_DIR}